### ISSUE TITLE
Ammo.cs is missing property "PenetrationPower" from JSON/data files

### ISSUE THREAD

**Issue by RichardForsey89** [RatScanner/RatStash#1]
As title, it's kind of a problem! 😛
Need to add:
```
[JsonProperty("PenetrationPower")]
        public int PenetrationPower { get; set; }
```

**Comment by Blightbuster** [comment]
While fixing this, I noticed **a lot** of other properties are also missing some which require custom converters. Im half way done with all of them now only missing med / food effects but Im not available over the weekend so the new release which contains them will arrive on monday.
