### ISSUE TITLE
RatStash.Weapon attribute name typo

### ISSUE THREAD

**Issue by RichardForsey89** [RatScanner/RatStash#2]
line 233 "RecolDispersion".

😛

**Comment by Blightbuster** [comment]
The typos are on BSG 😄 
![image](https://user-images.githubusercontent.com/24388294/198015904-93e357b9-6935-4ffc-ac75-7981ee75d812.png)

But yeah fixing it in the library makes sense.

**Comment by Blightbuster** [comment]
Thanks, fixed ❤️
